version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    versioning-strategy: increase
  - package-ecosystem: nuget
    directory: '/'
    schedule:
      interval: weekly
    versioning-strategy: increase
    