###
POST http://localhost:7071/api/ReceiveGameScoresFunction
Content-Type: application/json

[
    {
    "Nickname" : "John Doe",
    "Points" : 44,
    "Game" : "Pacman"
    },
    {
    "Nickname" : "Jane Doe",
    "Points" : 1337,
    "Game" : "Pacman"
    }
]